# This is a basic workflow to help you get started with Actions

name: trusted_resolvers

# Controls when the action will run. 
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo
      - uses: actions/checkout@v2
      
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
      
      - name: Checkout dnsvalidator
        run: git clone https://github.com/vortexau/dnsvalidator.git

      - name: Install dnsvalidator
        run: sudo python3 dnsvalidator/setup.py install
      
      - name: Run dnsvalidator
        run: dnsvalidator -tL https://public-dns.info/nameservers.txt -threads 20 -o wordlists/trusted_resolvers.txt
      
      - name: Create local changes
        run: git add wordlists/trusted_resolvers.json
      
      - name: Commit results to Github
        run: |
            git config --local user.email ""
            git config --global user.name "trusted_resolvers"
            git commit -m "Bot auto trusted_resolvers update" -a --allow-empty
            
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           branch: ${{ github.ref }}
